Cannot display user rating distribution for popular media. Somehow, the imdb_id is not being printed to the table for popular movies and tv. This issue does not happen with top 250. I'm lost as to why. All attempts at fixing bring me back to original error.
Traceback (most recent call last):
  File "/Users/michaelhebner/PycharmProjects/hebner_capstone/hebner_project1/view.py", line 169, in cell_clicked
    self.rating_window = GraphWindow(self.table.item(row, 6).text(), self.table.item(row, 0).text())
AttributeError: 'NoneType' object has no attribute 'text'

Column 6 is supposed to have the imdb_id but it will not add it. Therefore, when trying to get user ratings for a selection, there is no imdb_id to pass to get_user_ratingsV2.